<?php

if ( function_exists( 'acf_add_local_field_group' ) ) {

	acf_add_local_field_group(
		array(
			'key'                   => 'group_home_page',
			'title'                 => 'Home Page Fields',
			'fields'                => array(
				array(
					'key'               => 'field_hero_background_image',
					'label'             => 'Hero Background Image',
					'name'              => 'hero_background_image',
					'type'              => 'image',
					'instructions'      => 'Upload background image for hero section',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'front_page',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_profession',
			'title'                 => 'Profession Fields',
			'fields'                => array(
				array(
					'key'               => 'field_profession_custom_title',
					'label'             => 'Заголовок с городом',
					'name'              => 'profession_custom_title',
					'type'              => 'text',
					'instructions'      => 'Используйте шорткод [belingogeo_city_field field="city_padej1"] для подстановки названия города. Например: Обучение го и чс дистанционно в [belingogeo_city_field field="city_padej1"]',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => 'Обучение го и чс дистанционно в [belingogeo_city_field field="city_padej1"]',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_profession_min_price',
					'label'             => 'Минимальная стоимость',
					'name'              => 'profession_min_price',
					'type'              => 'text',
					'instructions'      => 'Минимальная стоимость для отображения в карточке (например: 3 500)',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '3 500',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_profession_tab_description',
					'label'             => 'Описание',
					'name'              => 'profession_tab_description',
					'type'              => 'wysiwyg',
					'instructions'      => 'Контент для вкладки "Описание"',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_profession_tab_pricing',
					'label'             => 'Стоимость обучения',
					'name'              => 'profession_tab_pricing',
					'type'              => 'repeater',
					'instructions'      => 'Добавьте программы обучения с ценами',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Добавить программу',
					'sub_fields'        => array(
						array(
							'key'               => 'field_profession_pricing_program',
							'label'             => 'Программа',
							'name'              => 'program',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_profession_pricing_hours',
							'label'             => 'Часы',
							'name'              => 'hours',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_profession_pricing_price',
							'label'             => 'Цена',
							'name'              => 'price',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'profession',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

}


