<?php

if ( function_exists( 'acf_add_local_field_group' ) ) {

	acf_add_local_field_group(
		array(
			'key'                   => 'group_home_page',
			'title'                 => 'Home Page Fields',
			'fields'                => array(
				array(
					'key'               => 'field_hero_background_image',
					'label'             => 'Hero Background Image',
					'name'              => 'hero_background_image',
					'type'              => 'image',
					'instructions'      => 'Upload background image for hero section',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_type',
						'operator' => '==',
						'value'    => 'front_page',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_profession',
			'title'                 => 'Profession Fields',
			'fields'                => array(
				array(
					'key'               => 'field_profession_custom_title',
					'label'             => 'Заголовок с городом',
					'name'              => 'profession_custom_title',
					'type'              => 'text',
					'instructions'      => 'Используйте шорткод [belingogeo_city_field field="city_padej1"] для подстановки названия города. Например: Обучение го и чс дистанционно в [belingogeo_city_field field="city_padej1"]',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => 'Обучение го и чс дистанционно в [belingogeo_city_field field="city_padej1"]',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_profession_min_price',
					'label'             => 'Минимальная стоимость',
					'name'              => 'profession_min_price',
					'type'              => 'text',
					'instructions'      => 'Минимальная стоимость для отображения в карточке (например: 3 500)',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '3 500',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_profession_tab_description',
					'label'             => 'Описание',
					'name'              => 'profession_tab_description',
					'type'              => 'wysiwyg',
					'instructions'      => 'Контент для вкладки "Описание"',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 1,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_profession_tab_pricing',
					'label'             => 'Стоимость обучения',
					'name'              => 'profession_tab_pricing',
					'type'              => 'repeater',
					'instructions'      => 'Добавьте программы обучения с ценами',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Добавить программу',
					'sub_fields'        => array(
						array(
							'key'               => 'field_profession_pricing_program',
							'label'             => 'Программа',
							'name'              => 'program',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_profession_pricing_hours',
							'label'             => 'Часы',
							'name'              => 'hours',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_profession_pricing_price',
							'label'             => 'Цена',
							'name'              => 'price',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'profession',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_courses_pdf',
			'title'                 => 'Настройки курсов для PDF',
			'fields'                => array(
				array(
					'key'               => 'field_courses_pdf_list',
					'label'             => 'Список курсов',
					'name'              => 'courses_pdf_list',
					'type'              => 'repeater',
					'instructions'      => 'Добавьте курсы с прикрепленными PDF файлами',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Добавить курс',
					'sub_fields'        => array(
						array(
							'key'               => 'field_course_name',
							'label'             => 'Название курса',
							'name'              => 'course_name',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_course_pdf',
							'label'             => 'Файл',
							'name'              => 'course_pdf',
							'type'              => 'file',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'library'           => 'all',
							'min_size'          => '',
							'max_size'          => '',
							'mime_types'        => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'acf-options',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_review',
			'title'                 => 'Поля отзыва',
			'fields'                => array(
				array(
					'key'               => 'field_review_name',
					'label'             => 'Имя',
					'name'              => 'review_name',
					'type'              => 'text',
					'required'          => 1,
					'wrapper'           => array(
						'width' => '50',
					),
				),
				array(
					'key'               => 'field_review_rating',
					'label'             => 'Рейтинг',
					'name'              => 'review_rating',
					'type'              => 'number',
					'instructions'      => 'Оценка от 1 до 5',
					'required'          => 1,
					'min'               => 1,
					'max'               => 5,
					'default_value'     => 5,
					'wrapper'           => array(
						'width' => '50',
					),
				),
				array(
					'key'               => 'field_review_course',
					'label'             => 'Курс',
					'name'              => 'review_course',
					'type'              => 'text',
					'instructions'      => 'Название курса (оставьте пустым для общего отзыва)',
					'required'          => 0,
					'wrapper'           => array(
						'width' => '100',
					),
				),
				array(
					'key'               => 'field_review_photo',
					'label'             => 'Фото',
					'name'              => 'review_photo',
					'type'              => 'image',
					'required'          => 0,
					'return_format'     => 'array',
					'preview_size'      => 'thumbnail',
					'library'           => 'all',
					'wrapper'           => array(
						'width' => '100',
					),
				),
				array(
					'key'               => 'field_review_approved',
					'label'             => 'Одобрен',
					'name'              => 'review_approved',
					'type'              => 'true_false',
					'instructions'      => 'Отображать отзыв на сайте',
					'default_value'     => 0,
					'ui'                => 1,
					'wrapper'           => array(
						'width' => '100',
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'review',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_quiz',
			'title'                 => 'Поля квиза',
			'fields'                => array(
				array(
					'key'               => 'field_quiz_questions',
					'label'             => 'Вопросы',
					'name'              => 'quiz_questions',
					'type'              => 'repeater',
					'instructions'      => 'Добавьте вопросы для квиза',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => 'field_question_text',
					'min'               => 1,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Добавить вопрос',
					'sub_fields'        => array(
						array(
							'key'               => 'field_question_text',
							'label'             => 'Текст вопроса',
							'name'              => 'question_text',
							'type'              => 'text',
							'required'          => 1,
							'wrapper'           => array(
								'width' => '',
							),
						),
						array(
							'key'               => 'field_question_answers',
							'label'             => 'Варианты ответов',
							'name'              => 'question_answers',
							'type'              => 'repeater',
							'instructions'      => 'Добавьте варианты ответов',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
							),
							'collapsed'         => '',
							'min'               => 2,
							'max'               => 0,
							'layout'            => 'table',
							'button_label'      => 'Добавить ответ',
							'sub_fields'        => array(
								array(
									'key'               => 'field_answer_text',
									'label'             => 'Текст ответа',
									'name'              => 'answer_text',
									'type'              => 'text',
									'required'          => 1,
									'wrapper'           => array(
										'width' => '',
									),
								),
								array(
									'key'               => 'field_answer_correct',
									'label'             => 'Правильный ответ',
									'name'              => 'answer_correct',
									'type'              => 'true_false',
									'instructions'      => 'Отметьте, если это правильный ответ',
									'required'          => 0,
									'default_value'     => 0,
									'ui'                => 1,
									'wrapper'           => array(
										'width' => '',
									),
								),
								array(
									'key'               => 'field_answer_points',
									'label'             => 'Баллы',
									'name'              => 'answer_points',
									'type'              => 'number',
									'instructions'      => 'Количество баллов за этот ответ',
									'required'          => 0,
									'default_value'     => 1,
									'min'               => 0,
									'max'               => 100,
									'wrapper'           => array(
										'width' => '',
									),
								),
							),
						),
					),
				),
				array(
					'key'               => 'field_quiz_results',
					'label'             => 'Результаты',
					'name'              => 'quiz_results',
					'type'              => 'repeater',
					'instructions'      => 'Настройте результаты в зависимости от набранных баллов',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
					),
					'collapsed'         => 'field_result_title',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Добавить результат',
					'sub_fields'        => array(
						array(
							'key'               => 'field_result_min_points',
							'label'             => 'Минимальные баллы',
							'name'              => 'result_min_points',
							'type'              => 'number',
							'required'          => 1,
							'wrapper'           => array(
								'width' => '50',
							),
						),
						array(
							'key'               => 'field_result_max_points',
							'label'             => 'Максимальные баллы',
							'name'              => 'result_max_points',
							'type'              => 'number',
							'required'          => 1,
							'wrapper'           => array(
								'width' => '50',
							),
						),
						array(
							'key'               => 'field_result_title',
							'label'             => 'Заголовок результата',
							'name'              => 'result_title',
							'type'              => 'text',
							'required'          => 1,
							'wrapper'           => array(
								'width' => '',
							),
						),
						array(
							'key'               => 'field_result_description',
							'label'             => 'Описание результата',
							'name'              => 'result_description',
							'type'              => 'textarea',
							'required'          => 0,
							'wrapper'           => array(
								'width' => '',
							),
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'quiz',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'          => '',
		)
	);

}


